"$schema" = "./node_modules/wrangler/config-schema.json"

name = "cinerenamelanding"
main = ".open-next/worker.js"
compatibility_date = "2026-04-28"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "cinerenamelanding"

[observability]
enabled = true

[vars]
LEMON_SQUEEZY_STORE_ID = "395231"
LEMON_SQUEEZY_MONTHLY_VARIANT_ID = "1844160"
LEMON_SQUEEZY_ANNUAL_VARIANT_ID = "1844161"
LEMON_SQUEEZY_LIFETIME_VARIANT_ID = "1844162"
NEXT_PUBLIC_LEMONSQUEEZY_URL = "https://store.cinerename.app/"
NEXT_PUBLIC_LEMONSQUEEZY_MONTHLY_URL = "https://store.cinerename.app/checkout/buy/eb75b5b5-35c4-4cbc-9706-07f8c3f23384"
NEXT_PUBLIC_LEMONSQUEEZY_ANNUAL_URL = "https://store.cinerename.app/checkout/buy/1c0c102c-d4f2-4c83-a097-ecffd3c87add"
NEXT_PUBLIC_LEMONSQUEEZY_LIFETIME_URL = "https://store.cinerename.app/checkout/buy/c8b7ccf1-197c-48ee-9a1a-646a2f843f41"
NEXT_PUBLIC_POSTHOG_KEY = "phc_sTdZScXnNLGmHnKpFouDBLVWf2R67gsKMHRAzwmcU4Dy"
NEXT_PUBLIC_POSTHOG_HOST = "https://eu.i.posthog.com"
