"$schema" = "./node_modules/wrangler/config-schema.json"

name = "cinerenamelanding"
main = ".open-next/worker.js"
compatibility_date = "2026-04-28"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "cinerenamelanding"

[observability]
enabled = true

[vars]
LEMON_SQUEEZY_STORE_ID = "395231"
LEMON_SQUEEZY_MONTHLY_PRODUCT_ID = "1109147"
LEMON_SQUEEZY_ANNUAL_PRODUCT_ID = "1109123"
LEMON_SQUEEZY_LIFETIME_PRODUCT_ID = "1109141"
NEXT_PUBLIC_POSTHOG_KEY = "phc_sTdZScXnNLGmHnKpFouDBLVWf2R67gsKMHRAzwmcU4Dy"
NEXT_PUBLIC_POSTHOG_HOST = "https://eu.i.posthog.com"

[build]
command = "npm run cf:build"
